export enum UserRole {
  ADMIN = 'ADMIN',
  BROKER = 'BROKER',
  MACHINERY_COMPANY = 'MACHINERY_COMPANY',
}

export enum OnboardingEntityType {
  BROKER = 'BROKER',
  MACHINERY_COMPANY = 'MACHINERY_COMPANY',
}

export enum OnboardingStatus {
  INVITED = 'INVITED',
  DOCS_SUBMITTED = 'DOCS_SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
}

export enum InvoiceStatus {
  DRAFT = 'DRAFT',
  UPLOADED = 'UPLOADED',
  EXTRACTING = 'EXTRACTING',
  PENDING_BROKER_REVIEW = 'PENDING_BROKER_REVIEW',
  PENDING_MC_APPROVAL = 'PENDING_MC_APPROVAL',
  MC_DISPUTED = 'MC_DISPUTED',
  PENDING_UNDERWRITING = 'PENDING_UNDERWRITING',
  INFO_REQUESTED = 'INFO_REQUESTED',
  REJECTED = 'REJECTED',
  APPROVED_FOR_FUNDING = 'APPROVED_FOR_FUNDING',
  FUNDED = 'FUNDED',
  SETTLED = 'SETTLED',
  CHARGED_BACK = 'CHARGED_BACK',
  WRITTEN_OFF = 'WRITTEN_OFF',
  CANCELLED = 'CANCELLED',
}

export enum ReserveHoldReasonCode {
  DISPUTE = 'DISPUTE',
  CREDIT_MEMO = 'CREDIT_MEMO',
  OFFSET = 'OFFSET',
  PRICING_CORRECTION = 'PRICING_CORRECTION',
  DELIVERY_ISSUE = 'DELIVERY_ISSUE',
  OTHER = 'OTHER',
}

export enum ChargebackReasonCode {
  FRAUD = 'FRAUD',
  DUPLICATE = 'DUPLICATE',
  INVALID_DATA = 'INVALID_DATA',
  PRICING_ERROR = 'PRICING_ERROR',
  DELIVERY_DISPUTE = 'DELIVERY_DISPUTE',
  CREDIT_MEMO = 'CREDIT_MEMO',
  OFFSET = 'OFFSET',
  OTHER = 'OTHER',
}

export enum ChargebackStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  WRITTEN_OFF = 'WRITTEN_OFF',
}

export enum DisputeStatus {
  OPEN = 'OPEN',
  RESOLVED = 'RESOLVED',
  REJECTED = 'REJECTED',
}

export enum PaymentStatus {
  UNMATCHED = 'UNMATCHED',
  PARTIALLY_MATCHED = 'PARTIALLY_MATCHED',
  FULLY_MATCHED = 'FULLY_MATCHED',
  OVERPAID = 'OVERPAID',
  UNDERPAID = 'UNDERPAID',
  DISPUTED = 'DISPUTED',
}

export enum LedgerEntryType {
  FUNDING_DISBURSEMENT = 'FUNDING_DISBURSEMENT',
  RESERVE_HOLD = 'RESERVE_HOLD',
  FEE_ACCRUAL = 'FEE_ACCRUAL',
  FEE_INVOICE = 'FEE_INVOICE',
  PAYMENT_RECEIPT = 'PAYMENT_RECEIPT',
  RESERVE_RELEASE = 'RESERVE_RELEASE',
  ADJUSTMENT = 'ADJUSTMENT',
  CHARGEBACK = 'CHARGEBACK',
  REPURCHASE = 'REPURCHASE',
  WRITE_OFF = 'WRITE_OFF',
  MANUAL_CORRECTION = 'MANUAL_CORRECTION',
}

export enum CreditLimitChangeReason {
  INVOICE_FUNDED = 'INVOICE_FUNDED',
  INVOICE_SETTLED = 'INVOICE_SETTLED',
  CHARGEBACK = 'CHARGEBACK',
  MANUAL_ADJUSTMENT = 'MANUAL_ADJUSTMENT',
}

export enum InvoiceDocumentType {
  INVOICE = 'INVOICE',
  POD = 'POD',
  DELIVERY_TICKET = 'DELIVERY_TICKET',
  OTHER = 'OTHER',
}

export enum ExtractionStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum NotificationStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
}
